// Writes app/sw-version.generated.ts with a token that is unique per build.
// The service worker is registered as /sw.js?v=<token>, so a changed token
// forces every client to see a new worker and pick up the new deploy on the
// next launch. Runs on `npm run dev`, `npm run build`, and postinstall.
//
// The generated file is git-ignored on purpose: it must reflect the machine
// that built the app, not whatever was last committed.

import { execSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

function buildToken() {
  const fromCi =
    process.env.VERCEL_GIT_COMMIT_SHA ||
    process.env.GITHUB_SHA ||
    process.env.CF_PAGES_COMMIT_SHA ||
    process.env.SOURCE_VERSION ||
    "";

  let fromGit = "";
  try {
    fromGit = execSync("git rev-parse --short HEAD", {
      stdio: ["ignore", "pipe", "ignore"],
    })
      .toString()
      .trim();
  } catch {
    // not a git checkout / git not installed — fine, fall through
  }

  const base = (fromCi && fromCi.slice(0, 12)) || fromGit || "local";
  // Append the build time so redeploying the same commit still bumps.
  return `${base}.${Date.now().toString(36)}`;
}

const token = buildToken();
const outFile = join(process.cwd(), "app", "sw-version.generated.ts");
const contents =
  `// AUTO-GENERATED by scripts/stamp-sw.mjs — do not edit, do not commit.\n` +
  `// Bumped on every dev/build so the service worker URL changes per deploy.\n` +
  `export const SW_VERSION = ${JSON.stringify(token)};\n`;

try {
  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(outFile, contents);
  console.log(`[stamp-sw] SW_VERSION = ${token}`);
} catch (err) {
  // Never fail install/build over this.
  console.warn(`[stamp-sw] skipped: ${(err && err.message) || err}`);
}
